title: KidneyGenAfrica Exercises
author: Jean-Tristan Brandenburg
email: jean-tristan.brandenburg@wits.ac.za
github_username: jeantristanb
theme: minima

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
