theme: jekyll-theme-minimal
title: KidneyGenAfrica Excercice
description: A place to share my projects and thoughts.
author: Jean-Tristan Brandenburg
email: jean-tristan.brandenburg@wits.ac.za
github_username: jeantristanb
markdown: kramdown
kramdown:
  input: GFM
